# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pasteai < Formula
  desc "AI publishes markdown documents via MCP. You read them in a clean, themed web UI."
  homepage "https://github.com/pasteai/pasteai"
  version "0.0.14"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pasteai/pasteai/releases/download/v0.0.14/pasteai_0.0.14_darwin_amd64.tar.gz"
      sha256 "c80e9fd158affd42b337b9004b3978a54112802afd27f5d8e3d584c9cb79b9ec"

      define_method(:install) do
        bin.install "pasteai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pasteai/pasteai/releases/download/v0.0.14/pasteai_0.0.14_darwin_arm64.tar.gz"
      sha256 "be9a616146b33527e212f9ddeb33c1b1ffcec3a2498dc286f5d30e394d117d60"

      define_method(:install) do
        bin.install "pasteai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pasteai/pasteai/releases/download/v0.0.14/pasteai_0.0.14_linux_amd64.tar.gz"
      sha256 "1bfe1a86c96c37b89934916640b197bc4cceeed18df024bee237ed1e17aa5814"
      define_method(:install) do
        bin.install "pasteai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pasteai/pasteai/releases/download/v0.0.14/pasteai_0.0.14_linux_arm64.tar.gz"
      sha256 "c6d9cdcc80c8bb13b33009e86ee05f2e34a2efe91b51523174c16e7007cb7546"
      define_method(:install) do
        bin.install "pasteai"
      end
    end
  end

  test do
    system "#{bin}/pasteai", "version"
  end
end
