# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pasteai < Formula
  desc "AI publishes markdown documents via MCP. You read them in a clean, themed web UI."
  homepage "https://github.com/pasteai/pasteai"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pasteai/pasteai/releases/download/v0.0.1/pasteai_0.0.1_darwin_amd64.tar.gz"
      sha256 "35bf56f2db3b95aa980885d078551bd77fec01689b15a52e9c3f8a2ec6a7d6ab"

      define_method(:install) do
        bin.install "pasteai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pasteai/pasteai/releases/download/v0.0.1/pasteai_0.0.1_darwin_arm64.tar.gz"
      sha256 "0ff75353fa549ae76c8dd6c58da5041b9045ce30b9b541290d91b818bade523c"

      define_method(:install) do
        bin.install "pasteai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pasteai/pasteai/releases/download/v0.0.1/pasteai_0.0.1_linux_amd64.tar.gz"
      sha256 "4d047b4cbeba909e7f47634f283c07947c3169e1428f8b69075ad1758a68411c"
      define_method(:install) do
        bin.install "pasteai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pasteai/pasteai/releases/download/v0.0.1/pasteai_0.0.1_linux_arm64.tar.gz"
      sha256 "2b77735791ce271ae9b32833e608f343b94bdaffa9a907dbf2cfccec52e29b02"
      define_method(:install) do
        bin.install "pasteai"
      end
    end
  end

  test do
    system "#{bin}/pasteai", "version"
  end
end
